apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Test_Demo1"
  annotations:
    github.com/project-slug: CHANDU0506/Test_Demo1
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: service
  owner: guests
  lifecycle: experimental
